### ISSUE TITLE
Demo page does not work on IE >= 10

### ISSUE THREAD

**Issue by soenkekluth** [garetmckinley/hedron#38]
see  http://jsb.ro/hedron

**Comment by soenkekluth** [comment]
so doesn't https://jsbros.github.io/uigradients/

console says:
```
SCRIPT438: Object doesn't support property or method 'startsWith' 
main.74785c5b.js, line 10 character 14226
```

**Comment by garetmckinley** [comment]
Is the console error the same for both sites? I don't generally test on IE, I guess I'm going to have to start 💁

**Comment by garetmckinley** [comment]
I got my Windows PC back up today and I was able to confirm this error. It seems to be because one of the libraries used requires the `string.startsWith()` method, which is not supported at all in IE. If I add a polyfill to the rollup configuration for it, we should be good on IE :ok_hand:

**Comment by soenkekluth** [comment]
yo. fuck IE in general! but better go with it cause many clients use them. and well - a grid system is a major part of the site layout - so it should word on fuck ;)

**Comment by garetmckinley** [comment]
Its not an issue with the grid system, just with the demo pages. Hedron functions as expected in IE versions supporting flexbox
