### ISSUE TITLE
Change the way hedron handles gutters

### ISSUE THREAD

**Issue by garetmckinley** [garetmckinley/hedron#46]
### From Slack:
![screen shot 2016-12-24 at 11 42 29 am](https://cloud.githubusercontent.com/assets/1624279/21467994/199cfed4-c9ce-11e6-98e3-06b97b21c77a.png)

So the above thought happened in the jsbro slack room. I want to integrate a better gutter system that better suits the "flexbox way".

Unfortunately, it appears I'm not far off from the "flexbox way"; as [this stackoverflow answer](http://stackoverflow.com/a/20653092) sums up that the best way he found to create flexbox gutters is via padding.

### So what's the issue?

It's more of a design choice than an issue, but here it is summed up:

If you have a row divided into 4 equal columns each with their own padding, a few interesting things happen:

- The `Row` gets 0 padding, it's treated as a fluid element
- Each of the `Column` components get rendered with a `20px` padding.
- The `20px` padding acts as a `40px` gutter.

The issue here is that the first and last Columns have their gutters halved because there's no elements on either side of them granting the additional `20px` padding. The solution for this lies inside the stackoverflow answer above, but unfortunately that creates another issue... Since the `Row` component would have padding, it becomes impossible to use the `fluid` property on `Columns` effectively. Since the best case scenario, is that the first and last `Columns` have a `20px` padding, while the others are sitting edge to edge.

This would then force me to add another property onto the `Row` component for `fluid`. Which means that to have fluid `Columns`, we would have to also add `fluid` to the parent `Row`.

### So why don't I do this?

It adds not only another layer of complexity to the grid layout, it also makes it *impossible* to mix fluid `Columns` with padded `Columns`, as the `fluid` property would have to be changed on the parent to make our `Column` sit up against the edge of the `Row`; which compromises that `20px` padding we want added to the `Column` on the other side.

**Comment by timscott** [comment]
The way padding is handled creates another problem. Consider this example:

```jsx
<Page>
  <Row>
    <Column>
      Hello
    </Column>
    <Column>
      <Row>
        <Column>
          World
        </Column>
      </Row>
    </Column>
  </Row>
</Page>
```

It will appear like this

```

  Hello

    World

```

In other words, nested rows and columns will recursively indent by the default padding amount. 

I could make evert column fluid, but no, because I want gutters and vertical padding of rows.

I believe old school grid systems handle this by putting negative right and left margins on rows. I'm not sure that's a good flexbox-y solution. But I'm not sure of a better way either.

**Comment by garetmckinley** [comment]
Yeah the biggest issue with using negative margins is that flexbox enables "wrapping", so using `:first-child` and `:last-child` selectors aren't reliable, since it's highly possible that the last/first child isn't the only child sitting against an edge. It's one of the last big pieces of the puzzle before I can release 1.0.0, but we're still a bit unsure the best way to implement it. I've tried a few different solutions, but none have been reliable every 100% of the time. Flexbox just introduces way too may edge cases.

The only way I've found to reliably solve it, has been disabling wrapping and enabling a negative margin. But this of course removes most of the benefits of using flexbox in a responsive environment, so it's not something that's possible for a release.

**Comment by achtan** [comment]
why dont u solve this like Bootstrap ? 
````
.row {
  margin:0 -15px;
}
.col-xx-xx {
  padding:0 15px;
}
````

**Comment by garetmckinley** [comment]
Because negative margins get completely messed up when wrapping (which is one of the biggest selling points of flexbox).

It would be great if there were a css rule to select the first element in that row. Something like 

```css
.col:first-column {
}
```

But I might be dreaming here.
