### ISSUE TITLE
Vertically centering rows

### ISSUE THREAD

**Issue by zsherman** [garetmckinley/hedron#49]
Is there a recommended way to do this or should we just specify whatever styles directly on the `<Page>` component?

**Comment by garetmckinley** [comment]
The way to officially handle this within flexbox is by using the `justify-content` property. I ported this property to hedron in the form on the `justifyContent` component property (outlined [here](https://github.com/JSBros/hedron/wiki/Grid-System#row-options) on the wiki).

[Here's an example](http://www.webpackbin.com/Ny59owCVG) of `justifyContent` in action. Let me know if this answers your question 😄

**Comment by garetmckinley** [comment]
Admittedly, I need to work on ramping up the wiki documentation. If you're not familiar with the flexbox system, it would be fairly obscure what the properties outlined in the wiki actually do. Seeing as the whole point of hedron is to abstract away the complicated flex stuff, I really need to document them better.

`justifyContent` sets the flex-align on the vertical axis, `alignContent` sets the flex-align on the horizontal axis. The values they accept are `stretch|center|flex-start|flex-end|space-between|space-around|initial|inherit`

**Comment by zsherman** [comment]
Oh yeah I'm familiar with flexbox, I was asking about centering rows within a page, not just centering inside the rows themselves.

**Comment by zsherman** [comment]
For now I just added my own flex styles in a `style` object but it would be nice if you could add flex attrs to the `<Page>` component

**Comment by garetmckinley** [comment]
Ah, sorry for misunderstanding. Yeah that's a valid workaround; would definitely be nice to add that feature, so thanks for the suggestion! Any ideas on what an ideal API would look like for you?

**Comment by zsherman** [comment]
Cool no worries, thanks for the library!

Thought the way http://roylee0704.github.io/react-flexbox-grid/ handles it was quite good/obvious.

**Comment by garetmckinley** [comment]
Thanks, I'll check it out 👍

**Comment by garetmckinley** [comment]
I have officially added this to the roadmap, feel free to drop by on #50 with any additional input/suggestions you might have before I begin the implementation 😄

**Comment by zsherman** [comment]
thanks @garetmckinley, will do!

**Comment by garetmckinley** [comment]
This is resolved in v1. Alignment, in general, is now much more flexible and the `Page` component has been removed.
