### ISSUE TITLE
Make the Page component more useful

### ISSUE THREAD

**Issue by garetmckinley** [garetmckinley/hedron#50]
Adding this issue as an official discussion thread for some new enhancements to the `Page` component. Currently this component functions as simply a wrapper. It defaults to `960px` wide and horizontally centered using `margin: 0 auto`. It also accepts the `debug` property and passes it on to all it's children.

It's usefulness stops there though, but I think it has the potential to be so much more; since it's essentially the top level component for your app.

The issue #49 is what inspired me to open up this discussion.

### `height`: `string` = `number[px|%|vh]`

```jsx
<Page height='50vh'>
  <Row>
    <Column>
      <h1>This page is exactly half the viewport height</h1>
    </Column>
  </Row>
</Page>
```

This would allow you to set a specific height for the `Page` component. In responsive design, it's generally not too useful to set a static `height` for your top-level component, but this would exist for those rare edge cases.

### `overflow`: `string` = `hidden|scroll`

```jsx
<Page height='100px' overflow='scroll'>
  <Row>
    <Column>
      <h1>This is a statically sized page that scrolls</h1>
      <h1>This is a statically sized page that scrolls</h1>
      <h1>This is a statically sized page that scrolls</h1>
      <h1>This is a statically sized page that scrolls</h1>
      <h1>This is a statically sized page that scrolls</h1>
    </Column>
  </Row>
</Page>
```

The `overflow` property is basically required if we add a `height` property. It would allow you to set the the action taken on all content that overflows (a mirror of the css `overflow` property)

### `fullscreen`: `boolean` = `true|false`

```jsx
<Page fullscreen>
  <Row>
    <Column>
      <h1>This is a fullscreen component</h1>
    </Column>
  </Row>
</Page>
```

If this property exists, it would completely take priority over the `width|height` properties, however the `overflow` property would still be useful when using `fullscreen`. When it's set to true, it would set the `width` to `100vw` and `height` to `100vh`. The biggest issue I see here, is that the `body` has a `margin` on it by default, so it would be up to the user of hedron to disable this margin.

The only workaround I see for the default `body` margin, would be using `position: absolute; top: 0; left: 0;`. However, this seems like a hacky approach IMO, and not something I'm too eager to implement. _This is something that needs discussion._

### flex properties (#49)

Integrating the same general flex properties that are available on `Row` to the `Page` component would mean greater control over the alignment of the top-level rows without the need for advanced nesting. It would allow you to do stuff like this for vertical-alignments

```jsx
<Page fullscreen justifyContent='center'>
  <Row>
    <Column>
      <h1>This is a fullscreen component with vertically aligned text</h1>
    </Column>
  </Row>
</Page>
```

```jsx
<Page fullscreen justifyContent='flex-end'>
  <Row>
    <Column>
      <h1>This text appears on the very bottom of the viewport</h1>
    </Column>
  </Row>
</Page>
```

*However*, since this is a fairly opinionated grid system, the `Page` component is _expecting_ the very next component to be a `Row`; and since `Row` components are not meant to be next to each other, IMO we can remove the options for horizontal alignment. In that case, it might be better to abstract away the `justifyContent` property into something like `vAlign` or `verticalAlign`.

```jsx
<Page fullscreen verticalAlign='middle|top|bottom'>
  <Row>
    <Column>
      <h1>This is a fullscreen component with vertically aligned text</h1>
    </Column>
  </Row>
</Page>
```

As always, I'm open to discussing these further before implementing them, as well as any additional property requests that would be useful to add to the `Page` component 😄

**Comment by garetmckinley** [comment]
I'm also in the process of integrating react-storybook for visual testing of the grid system. It gave me the idea to implement another property for debugging (something like `debugColor`), to set an absolute color for the debug boxes.

![screen shot 2016-12-30 at 10 10 23 am](https://cloud.githubusercontent.com/assets/1624279/21567201/496bacf6-ce78-11e6-9699-845947347f47.png)

It's made to be super transparent so that nesting becomes increasingly more visible the deeper you go, but I'm thinking it might also be worthwhile to allow a custom color to be set. However, I'm not keen on the idea of adding another property just for debugging though, it would be cool if many the existing `debug` property could be used like so

```jsx
<Page debug='rgba(255, 0, 0, 0.1'>
    <Row><Column xs={1} /></Row>
    <Row><Column xs={2} /></Row>
    <Row><Column xs={3} /></Row>
    <Row><Column xs={4} /></Row>
    <Row><Column xs={5} /></Row>
    <Row><Column xs={6} /></Row>
    <Row><Column xs={7} /></Row>
    <Row><Column xs={8} /></Row>
    <Row><Column xs={9} /></Row>
    <Row><Column xs={10} /></Row>
    <Row><Column xs={11} /></Row>
    <Row><Column xs={12} /></Row>
</Page>
```

and if the `debug` prop is not set, it will disable debug mode. The biggest issue for this, is that it is not backwards compatible. So if this approach is taken, it shouldn't be deployed until the official 1.0.0 release (for SemVer).

It would also be cool if we could abstract away the opacity of debugging, so that nesting is always intact and not the responsibility of the user; i.e. `<Page debug='red' />` would render as `<Page debug='rgba(255, 0, 0, 0.1)' />`.

**Comment by mandriv** [comment]
I don't think most of these props would be useful, maybe except the flexbox-related ones. Setting custom height or overflow should be done through extending the Page component IMO.
