### ISSUE TITLE
is it possible to get rid of the default padding top on a column

### ISSUE THREAD

**Issue by dnecklesportfolio** [garetmckinley/hedron#73]
i tried adding 
![image](https://cloud.githubusercontent.com/assets/2013689/26028198/86889f92-37e9-11e7-82e4-ec9d718dda17.png)
where right is
![image](https://cloud.githubusercontent.com/assets/2013689/26028200/8cff4600-37e9-11e7-8d66-1a07d1358a2c.png)

but it didnt work.. is my syntax the problem

**Comment by garetmckinley** [comment]
The property is called ´style´ but you have ´styles´ written. Its a mistake I used to make all the time, rename it and it should work.

**Comment by therealedsheenan** [comment]
uhm `fluid` option?

```
<Column fluid sm={1}>
```

**Comment by garetmckinley** [comment]
That would work to remove all the padding, but I think he's just trying to remove the top padding.

**Comment by therealedsheenan** [comment]
I just find it inconsistent when you inline the styles on styled-components.

I think the `const NewColumn = styled(Column)` is more consistent code for me.
