### ISSUE TITLE
Parse error when implement both justifycontent/alignitems on Row component

### ISSUE THREAD

**Issue by Ron-Yu** [garetmckinley/hedron#83]
When I  implement both  justifycontent and alignitems props on Row component, it seems that parse error. If I just implement either justifycontent or alignitems, everything is fine.

![image](https://user-images.githubusercontent.com/5327305/28060036-9b2d76dc-6658-11e7-893c-f29599c513d0.png)

**Comment by garetmckinley** [comment]
Thanks for the report! Looks like it might be getting caused from a missing semi-colon in the styles. I'll look into it and try to get a patch published tomorrow 😄

**Comment by Ron-Yu** [comment]
hello, is there any feedback ? 😎

**Comment by garetmckinley** [comment]
Fixed in v1
