### ISSUE TITLE
Struggling to change margins

### ISSUE THREAD

**Issue by kdosburn** [garetmckinley/hedron#84]
Any help is greatly appreciated!

**Comment by garetmckinley** [comment]
Are you referring to the padding? If you're not using the `@next` version of hedron, there's no real elegant solutions.

Your options for changing the padding are:
#### Overriding via inline styles

```jsx
<Row><Column style={{ padding: '5px' }}>5px padding!</Column></Row>
```

#### Overriding via styled-components

```jsx
const StyledColumn = styled(Column)`
  padding: 5px;
`;

...
<Row><StyledColumn>5px padding!</StyledColumn></Row>
```


If you're talking about shifting elements via margin-left` , you can do that with [the shift properties](https://github.com/JSBros/hedron/wiki/Grid-System#column-options)

If you want more control over the grid system, I highly recommend checking out the [1.0.0 branch](https://github.com/JSBros/hedron/tree/1.0.0). Live example [here](http://hedron.rocks). The `LayoutProvider`  is super useful.
