### ISSUE TITLE
Extending Row & Column styling

### ISSUE THREAD

**Issue by apacicaps** [garetmckinley/hedron#86]
Hi,
I'm trying to use Hedron, but I'm running into trouble, when I try to extend Row and Column.
I need to set e.g. background-image, background-color, etc.

```
import React, { Component } from 'react';
import styled from 'styled-components';
import {Page, Row, Column } from 'hedron';

const DefRow = styled(Row) `
  background: papayawhip;
`;

const DefCol = styled(Column) `
  background: mediumaquamarine;
`;

class App extends Component {
  render() {
    return (
      <Page>
        <DefRow divisions={24}>
          <DefCol lg={12}>col1</DefCol>
          <DefCol lg={12}>col2</DefCol>
        </DefRow>
      </Page>
    );
  }
}

export default App;

```

But when I then use my DefRow and DefCol, they become kind of "double nested" and all columns fill out the entire width instead of being e.g. one third of the row.
Any suggestions for a fix? Am I maybe extending in a wrong way?

**Comment by garetmckinley** [comment]
So it looks like for whatever reason `divisions` isn't working, but the rest of the code is! I'll look into it, but for now maybe just try using a 12 division grid: https://www.webpackbin.com/bins/-KpzlAWHX6cmDgGhP8FZ

**Comment by apacicaps** [comment]
Thank you for looking into it :)

**Comment by mandriv** [comment]
@garetmckinley I think `divisions` prop is generally not working

**Comment by saraegtved** [comment]
Since this is still open, I just wanted to let you know, that we created our own grid system, which supports 24 columns.

**Comment by gerrymi** [comment]
Any updates on this? It seems like the divisions prop in Row isn't being properly passed down to the Columns. For now I'm working around this by manually setting the Column's divisions prop.

**Comment by mandriv** [comment]
@gerrymi I'll investigate this  once https://github.com/JSBros/hedron/pull/99 is merged

**Comment by garetmckinley** [comment]
1.0.0 did away with the concept of divisions, and embraces the way flex was meant to be used. There are also lots of CSS properties that are now exposed to the components. So you can do stuff like:

```jsx
<Grid.Bounds>
  <Grid.Box background="#ff00ff" color="#fff">Custom Styles!</Grid.Box>
</Grid.Bounds>
```
