### ISSUE TITLE
Error: Can't resolve 'styled-components'

### ISSUE THREAD

**Issue by stephenmathieson** [garetmckinley/hedron#87]
Recently updated `hedron`, but it seems to be missing a dependency:

```
ERROR in ./node_modules/hedron/dist/hedron.js
Module not found: Error: Can't resolve 'styled-components' in '/Users/stephenmathieson/dev/src/github.com/stephenmathieson/someapp/node_modules/hedron/dist'
 @ ./node_modules/hedron/dist/hedron.js 2:99-127
 @ ./src/pages/index.js
 @ ./src/routes.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/index.js
```

Maybe we should make note of the fact that you _must_ have `styled-components` installed in order to use `hedron` in the README?

**Comment by stephenmathieson** [comment]
Ah, it's a peer dep. I see Yarn warning me about it now.

Why is it a peer dep?

**Comment by garetmckinley** [comment]
It was done before there was a ton of optimizing on styled-components, so including sc increased the bundle size dramatically. Also it was around the time the community was split between v1 and v2. Now that it's optimized more and v2 is officially released, we can probably start packaging it back in. If you wanna submit a PR with it included that'd be great 😄

**Comment by iktl** [comment]
As a counterpoint to this, on projects that are otherwise using `styled-components` having it as a peer dependency is preferable to ending up with it bundled twice.

**Comment by stephenmathieson** [comment]
@garetmckinley sure thing, PR incoming!

@iktl your bundler should handle this for you. Both `browserify` and `webpack` do this by default.

**Comment by iktl** [comment]
@stephenmathieson: Perhaps my understanding and configuration of Webpack is flawed; when I look at my bundle with an analyzer I can see that `styled-components` is included in my primary bundle and also again as a child of `hedron`.

As far as I'm aware, Webpack can't dedupe between a project's source that it's building, and pre-built code from an NPM package. If I'm missing something though let me know and I can fix it on my end.

**Comment by garetmckinley** [comment]
Yeah this is actually something I've been thinking about a lot recently, and is one of the reasons styled-components was moved to a peer dependency.

Including styled-components inside hedron will cause it to be included twice in your app bundle. It shouldn't be a *huge* deal since styled-components has shrunk a lot in size (14kb gzipped I believe), but any extra kb is bad kb. Since hedron is advertised as a styled-components based flexbox system, I don't think it's a deal breaker to require users to include styled-components in their own app bundle.

I honestly think that's a better solution than including unnecessary dependencies in their bundle.

**Comment by garetmckinley** [comment]
Also, even if your bundler could dedupe (which as @iktl,  I don't think webpack is capable of doing ) the extra dependency, in order for that to happen the user would have to be using an identical version of styled-components as hedron is using (which would hardly ever happen).

**Comment by garetmckinley** [comment]
I think I'm just gonna bite the bullet and say "fuck it, ship it" to hedron `1.0.0` this weekend. I'll update the docs to mention that styled-components is a requirement to have, and give a brief explanation of why. If you have any objections or reasons why that's a bad idea, let me hear them. But most people who use hedron found it through styled-components, so they're likely already using it.
