### ISSUE TITLE
A fourth breakpoint.

### ISSUE THREAD

**Issue by yasserhennawi** [garetmckinley/hedron#90]
Can this lib. by any means supports more than 3 breakpoints (including the one before all of them xs) ?

**Comment by brandtnew** [comment]
Would be really awesome!

**Comment by mandriv** [comment]
It's now possible in 1.0.0! 🎉 Use `breakpoints` prop in `<Grid.Provider>`. 

According to README:
`breakpoints: { key: [int, int] }` - structure: `{ name: [min, max]}`
Defining breakpoints gives you strong control over the way your content is rendered at various screen sizes. Any property that can be set on Grid.Box can be set per-breakpoint. Here's a few things to keep in mind when defining breakpoints:

* Breakpoints can be named whatever you'd like (with a few exceptions laid out in the next section)
* When defining breakpoints, you must pass an array object containing only two values: the min and max (both must be integers)
* Breakpoints can have overlapping values. Use responsibly though, as it's possible to produce unexpected results when setting conflicting values on a Grid.Box with overlapping breakpoints. i.e. if mobile and tablet have overlapping pixels, don't make a Grid.Box hide on mobile and show on tablet.

**Comment by garetmckinley** [comment]
@mandriv I gotta update that part of the readme, there's actually a different syntax for breakpoints.

An example would look like this:

```jsx
<Grid.Provider breakpoints={{ mobile: "-500", laptop: "750-1000'", wide: "+1200" }}></Grid.Provider>
```

The language is basically:

- `-500` == 500px or less
- `750-1000` == 750px - 1000px
- `+1200` == 1200px or greater

**Comment by yasserhennawi** [comment]
Horay!! Thanks a lot guys, appreciate the good work so much ❤️

**Comment by garetmckinley** [comment]
@yasserhennawi if you upgrade to `hedron@next` and run into any issues, either open an issue here or open a thread on the [spectrum chat](https://spectrum.chat/hedron). I'm doing a lot of testing over the weekend and will release an official `1.0.0` on Monday :smile:
