### ISSUE TITLE
[v1] naming proposal

### ISSUE THREAD

**Issue by achtan** [garetmckinley/hedron#91]
Hi, i was a bit confused when i saw the new components naming.

my proposal is :
_current name -> new name_
Section -> Container
Container -> Grid
Box -> Cell

**Comment by garetmckinley** [comment]
I think I like that better than Container/Box, but the only thing I'm concerned about is that Grid implies a 2d matrix. Also there's possible confusion with the recent introduction of css grid.

**Comment by achtan** [comment]
ok, so what about:
Container -> Matrix :)
