### ISSUE TITLE
Having a prop for setting the gap between columns

### ISSUE THREAD

**Issue by florinpop17** [garetmckinley/hedron#96]
Would be nice to have a prop to be able to set the **padding** value of the column gaps. Currently is hardcoded to 20px. What do you think?

**Comment by brandtnew** [comment]
I would love to have this option too!

**Comment by mandriv** [comment]
Props like `p`, `m`, `px`, `py` and `mx`, `my` like in https://github.com/jxnblk/grid-styled would come very useful.

Right now I am just creating extended component like so:

```jsx
import { Column } from 'hedron';

const MyColumn = styled(Column)`
  margin: 15px 15px; 
`;

export default MyColumn;

**Comment by garetmckinley** [comment]
This is possible in the latest version of hedron. You can adjust the global padding with the `Grid.Provider` and also with individual grid elements. You can also adjust most other stylistic properties like margin, background, and more. You can checkout the docs [here](https://github.com/garetmckinley/hedron#documentation)
