### ISSUE TITLE
Outdated peer dependencies

### ISSUE THREAD

**Issue by mandriv** [garetmckinley/hedron#97]
Hey guys, first of all - great library, many thanks.

A small issue with `react` and `styled-components` peer dependencies - these are set for quite outdated versions right now.

```bash
warning " > hedron@0.7.1" has incorrect peer dependency "react@^15.0.0".
warning " > hedron@0.7.1" has incorrect peer dependency "styled-components@1.1.3 || ^2.0.0".
```

Could you update these to use e.g. `react@^16.0.0` and `styled-components@^3.0.0`? That's the setup I am currently using your library and it is working sweet (except for divisions prop I mentioned in another issue).

Have a great day, cheers!
Wojtek

**Comment by mandriv** [comment]
This is an important issue, can I get any response from the repo maintainers? I could help develop this library further, but right now I am thinking about switching to alternative solutions for my current project.

**Comment by gareteliot** [comment]
@mandriv are you still using hedron? I apologize deeply, I've been on a development sabbatical for a while now, been dreading digging through all my notifications on here. If you're interested in working with maintaining hedron, I can add you on the repo.

**Comment by mandriv** [comment]
Hi @gareteliot thanks for getting back to me. We are still using hedron so If possible, I'd love to work on some of the current issues.

**Comment by gareteliot** [comment]
No problem! Feel free to submit a PR! I'll add you to the org
